### PR TITLE
Adds some nice to have functions

### PR DESCRIPTION
**Pull request by stoeffel**
This adds some "nice to have" functions.
I also ran the code through elm-format. I hope that's okay for you.

Cheers

### CODE REVIEW

**Comment by joneshf** [comment]
Sorry, I totally missed your PR.

I love most of this, thanks!

I'm not so enthused about the predicate functions though. These sorts of functions are one place where I feel `core` has taken the correct approach with `Maybe a` and `Result a b`.

In the small it's not much of a problem. When the program is less than a couple hundred lines, using a predicate function is not that big of a deal. In the large though, providing and using a predicate function like this leads to unclear code. I'd rather it be more painful in the small than in the large.

---

There's a ton of information on this subject that is very hard to find :). Here are a bunch of links that provide more context:
- A somewhat abstract explanation of the situation.
  
  https://existentialtype.wordpress.com/2011/03/15/boolean-blindness/
- An explanation of the first article.
  
  http://www.hxa.name/notes/note-hxa7241-20131124T0927Z.html
- A more concrete explanation of the first article.
  
  https://news.ycombinator.com/item?id=4148307
- Lecture notes on communicating through types.
  
  https://www.cs.cmu.edu/~15150/previous-semesters/2012-spring/resources/lectures/09.pdf
- Proposition approach.
  
  https://www.reddit.com/r/programming/comments/15njic/dont_fall_prey_to_boolean_blindness_boolean_tests/c7o2yhb
- Specifically the addendum.
  
  http://degoes.net/articles/destroy-all-ifs#addendum
- Quick read on using evidence instead of booleans.
  
  http://cs-syd.eu/posts/2016-07-24-overcoming-boolean-blindness-evidence.html

**Comment by stoeffel** [comment]
Thanks for the links. Will remove the predicate functions.

**Comment by joneshf** [comment]
Thanks again!

**Comment by joneshf** [comment]
Also, made you a collaborator, so you're not waiting on me in the future.

**Comment by stoeffel** [comment]
Hey, Thanks for adding me as a collaborator and merging!
I will hopefully contribute more to your awesome modules in the future!
btw. I once experimented on a similar type https://gist.github.com/stoeffel/21b0d1a316edf76a7994c906b7006d5a. It's not as nice as elm-these and it isn't complete or anything, just felt about sharing it with you😀 (maybe you already saw it)

**Comment by joneshf** [comment]
I didn't see it, but it looks awesome!

**Comment by joneshf** [comment]
As mentioned in #3, I feel bad for shooting down the predicate functions. If you find them useful, we should add them.

Unfortunately, past-Hardy tried to be too smart and squashed your commits, so it's not as simple as a revert of 0f6a243845cb68a595a0638df6cd204ce7a67d17. I can make a new PR though if you're cool with it. Or you can make one if you'd prefer–seems like an unnecessary burden though.

**Comment by stoeffel** [comment]
> As mentioned in #3, I feel bad for shooting down the predicate functions. If you find them useful, we should add them.

I don't like those predicate functions anymore :-D. You know where I stand on booleans ;-)

**Pull request merged**
